# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jianjiUID.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_jianjiD(object):
    def setupUi(self, jianjiD):
        jianjiD.setObjectName("jianjiD")
        jianjiD.resize(800, 700)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(jianjiD)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_left = QtWidgets.QWidget(jianjiD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_left.sizePolicy().hasHeightForWidth())
        self.widget_left.setSizePolicy(sizePolicy)
        self.widget_left.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget_3 = QtWidgets.QListWidget(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_2.addWidget(self.listWidget_3)
        self.add_3 = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_3.sizePolicy().hasHeightForWidth())
        self.add_3.setSizePolicy(sizePolicy)
        self.add_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.add_3.setObjectName("add_3")
        self.verticalLayout_2.addWidget(self.add_3)
        self.horizontalLayout_2.addWidget(self.widget_left)
        self.widget_bottom = QtWidgets.QWidget(jianjiD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_bottom.sizePolicy().hasHeightForWidth())
        self.widget_bottom.setSizePolicy(sizePolicy)
        self.widget_bottom.setObjectName("widget_bottom")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_bottom)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wgt_video_2 = myVideoWidget(self.widget_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_video_2.sizePolicy().hasHeightForWidth())
        self.wgt_video_2.setSizePolicy(sizePolicy)
        self.wgt_video_2.setObjectName("wgt_video_2")
        self.verticalLayout.addWidget(self.wgt_video_2)
        self.widgetcentral_cen = QtWidgets.QWidget(self.widget_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetcentral_cen.sizePolicy().hasHeightForWidth())
        self.widgetcentral_cen.setSizePolicy(sizePolicy)
        self.widgetcentral_cen.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widgetcentral_cen.setObjectName("widgetcentral_cen")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetcentral_cen)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok = QtWidgets.QPushButton(self.widgetcentral_cen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok)
        self.play_3 = QtWidgets.QToolButton(self.widgetcentral_cen)
        self.play_3.setMaximumSize(QtCore.QSize(50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Desktop/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_3.setIcon(icon)
        self.play_3.setIconSize(QtCore.QSize(130, 70))
        self.play_3.setObjectName("play_3")
        self.horizontalLayout.addWidget(self.play_3)
        self.widget = QtWidgets.QWidget(self.widgetcentral_cen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.sld_video_6 = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sld_video_6.sizePolicy().hasHeightForWidth())
        self.sld_video_6.setSizePolicy(sizePolicy)
        self.sld_video_6.setMaximum(100)
        self.sld_video_6.setOrientation(QtCore.Qt.Horizontal)
        self.sld_video_6.setObjectName("sld_video_6")
        self.gridLayout.addWidget(self.sld_video_6, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.sld_video_2 = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sld_video_2.sizePolicy().hasHeightForWidth())
        self.sld_video_2.setSizePolicy(sizePolicy)
        self.sld_video_2.setMaximum(100)
        self.sld_video_2.setSliderPosition(100)
        self.sld_video_2.setOrientation(QtCore.Qt.Horizontal)
        self.sld_video_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sld_video_2.setObjectName("sld_video_2")
        self.gridLayout.addWidget(self.sld_video_2, 1, 1, 1, 2)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.widgetcentral_cen)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout.addWidget(self.textBrowser_3)
        self.horizontalLayout_2.addWidget(self.widget_bottom)

        self.retranslateUi(jianjiD)
        QtCore.QMetaObject.connectSlotsByName(jianjiD)

    def retranslateUi(self, jianjiD):
        _translate = QtCore.QCoreApplication.translate
        jianjiD.setWindowTitle(_translate("jianjiD", "Dialog"))
        self.add_3.setText(_translate("jianjiD", "添加文件"))
        self.ok.setText(_translate("jianjiD", "确认"))
        self.play_3.setText(_translate("jianjiD", "..."))
        self.label.setText(_translate("jianjiD", "from"))
        self.label_3.setText(_translate("jianjiD", "to"))
        self.textBrowser_3.setHtml(_translate("jianjiD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Log:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

from myVideoWidget import myVideoWidget
